'use client';
import { useEffect, useState } from 'react';

export default function RemoteConfigPage() {
  const [form,setForm]=useState({shareRate:80,minimumWithdrawal:10000,banner:{enabled:true,title:'',message:'',actionUrl:''}});
  const [state,setState]=useState('');
  useEffect(()=>{fetch('/api/app/config').then(r=>r.json()).then(d=>{const c=d.config||{};setForm({shareRate:Number(c.share_rate??80),minimumWithdrawal:Number(c.minimum_withdrawal??10000),banner:c.home_banner||{enabled:true,title:'',message:'',actionUrl:''}})});},[]);
  const save=async()=>{setState('Đang lưu...');const r=await fetch('/api/app/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setState(r.ok?'Đã cập nhật — app sẽ nhận cấu hình mới tự động.':'Không thể lưu cấu hình.');};
  return <div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-black text-slate-900">Remote config ứng dụng</h1><p className="text-sm text-slate-500 mt-1">Thay đổi chính sách và banner mà không cần phát hành APK mới.</p></div><div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-5"><label className="block text-sm font-bold">Tỷ lệ chia sẻ (%)<input type="number" min="0" max="100" value={form.shareRate} onChange={e=>setForm({...form,shareRate:Number(e.target.value)})} className="mt-2 w-full border rounded-xl px-4 py-3"/></label><label className="block text-sm font-bold">Mức rút tối thiểu (đ)<input type="number" min="0" value={form.minimumWithdrawal} onChange={e=>setForm({...form,minimumWithdrawal:Number(e.target.value)})} className="mt-2 w-full border rounded-xl px-4 py-3"/></label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.banner.enabled} onChange={e=>setForm({...form,banner:{...form.banner,enabled:e.target.checked}})}/> Hiện banner trang chủ</label><label className="block text-sm font-bold">Tiêu đề<input value={form.banner.title} onChange={e=>setForm({...form,banner:{...form.banner,title:e.target.value}})} className="mt-2 w-full border rounded-xl px-4 py-3"/></label><label className="block text-sm font-bold">Nội dung<textarea value={form.banner.message} onChange={e=>setForm({...form,banner:{...form.banner,message:e.target.value}})} className="mt-2 w-full border rounded-xl px-4 py-3 min-h-24"/></label><button onClick={save} className="bg-blue-600 text-white rounded-xl px-5 py-3 font-bold">Lưu và áp dụng</button><span className="ml-3 text-sm text-slate-500">{state}</span></div></div>;
}
